blank_issues_enabled: true
contact_links:
  - name: Questions
    url: https://github.com/Qonfused/ASUS-ZenBook-Pro-Duo-15-UX581-Hackintosh/discussions/new
    about: Please ask and answer questions here.
